//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleFacturas
    {
        public DetalleFacturas()
        {
            this.NotaCredito = new HashSet<NotaCredito>();
        }
    
        public int IdDetalleFactura { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public int idFactura { get; set; }
        public int idCodigoProducto { get; set; }
        public int AreaCalculada { get; set; }
        public int AreaTotal { get; set; }
        public int VentaRollo { get; set; }
        public int UnitVentam2 { get; set; }
        public int VentaNeta { get; set; }
        public int VentaIva { get; set; }
        public int VentaTotal { get; set; }
        public int PrecioLista { get; set; }
        public int PrecioCliente { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime FechaActualizacion { get; set; }
        public decimal Ancho { get; set; }
        public decimal Largo { get; set; }
    
        public virtual Facturas Facturas { get; set; }
        public virtual Productos Productos { get; set; }
        public virtual ICollection<NotaCredito> NotaCredito { get; set; }
    }
}
