//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PapiroWebEntities : DbContext
    {
        public PapiroWebEntities()
            : base("name=PapiroWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Ciudades> Ciudades { get; set; }
        public DbSet<Clientes> Clientes { get; set; }
        public DbSet<Comunas> Comunas { get; set; }
        public DbSet<ContactoComercial> ContactoComercial { get; set; }
        public DbSet<Departamento> Departamento { get; set; }
        public DbSet<TipoCargo> TipoCargo { get; set; }
        public DbSet<TipoPago> TipoPago { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
    }
}
