//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PapiroWebEntities : DbContext
    {
        public PapiroWebEntities()
            : base("name=PapiroWebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Ciudades> Ciudades { get; set; }
        public DbSet<Clientes> Clientes { get; set; }
        public DbSet<Comunas> Comunas { get; set; }
        public DbSet<ContactosComerciales> ContactosComerciales { get; set; }
        public DbSet<Departamentos> Departamentos { get; set; }
        public DbSet<DetalleFacturas> DetalleFacturas { get; set; }
        public DbSet<Facturas> Facturas { get; set; }
        public DbSet<Productos> Productos { get; set; }
        public DbSet<TipoProducto> TipoProducto { get; set; }
        public DbSet<TiposCargos> TiposCargos { get; set; }
        public DbSet<TiposPagos> TiposPagos { get; set; }
        public DbSet<Usuarios> Usuarios { get; set; }
        public DbSet<Ventas> Ventas { get; set; }
    }
}
