//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Productos
    {
        public Productos()
        {
            this.DetalleFacturas = new HashSet<DetalleFacturas>();
            this.Ventas = new HashSet<Ventas>();
        }
    
        public int IdProducto { get; set; }
        public int Codigo { get; set; }
        public int Codigo2 { get; set; }
        public int Descripcion { get; set; }
        public int Stock { get; set; }
        public Nullable<int> Precio { get; set; }
        public Nullable<int> IdTipoProducto { get; set; }
    
        public virtual ICollection<DetalleFacturas> DetalleFacturas { get; set; }
        public virtual TipoProducto TipoProducto { get; set; }
        public virtual ICollection<Ventas> Ventas { get; set; }
    }
}
