//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoProducto
    {
        public TipoProducto()
        {
            this.Productos = new HashSet<Productos>();
        }
    
        public int IdTipoProducto { get; set; }
        public string TipoProducto1 { get; set; }
    
        public virtual ICollection<Productos> Productos { get; set; }
    }
}
