//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoPago
    {
        public TipoPago()
        {
            this.Clientes = new HashSet<Clientes>();
        }
    
        public int IdTipoPago { get; set; }
        public string NombreTipoPago { get; set; }
    
        public virtual ICollection<Clientes> Clientes { get; set; }
    }
}
