//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace papiro.DALC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public Usuarios()
        {
            this.Facturas = new HashSet<Facturas>();
            this.NotaCredito = new HashSet<NotaCredito>();
        }
    
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public int IdDepartamento { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
        public virtual ICollection<Facturas> Facturas { get; set; }
        public virtual ICollection<NotaCredito> NotaCredito { get; set; }
    }
}
